feat: support xml files
splunk/addonfactory-workflow-requirement-files-unit-tests pull request #9
Opened 2022-02-24 23:28 UTC by nandinivij

2022-02-28 17:30 UTC, arys-splunk requested changes
Can we have a function to return a list of files that we want to check and reuse it everywhere? 
In case we want to change something in the future, we will need to apply the change only once.

2022-02-28 17:41 UTC, nandinivij commented
> Can we have a function to return a list of files that we want to check and reuse it everywhere? In case we want to change something in the future, we will need to apply the change only once.

Do we want to display the mismatched files? How do we decide if .log is a failure or .XML? By count?

2022-02-28 19:14 UTC, hsekowski-splunk requested changes

2022-02-28 19:31 UTC, nandinivij commented on test_lib/xml_format_checker.py
> +            else:
1. It is not allowed to have anything other than "*.log" and now *.xml are allowed too
2. I will add a check for empty directory

2022-02-28 19:35 UTC, nandinivij commented on test_lib/xml_format_checker.py
> +            if contains_XML and contains_log:
This condition will be true if we have a mixture of.xml and .log files in the requirement test folder. This is not allowed as if we have both *.xml and *.log files might coz confusion. It was a check requested to be added to avoid confusion

2022-03-01 21:53 UTC, nandinivij commented on test_lib/xml_format_checker.py
> +        contains_log, contains_XML, test_status = False, False, True
The condition to check and fail the test if we have a combination of . XML or .log will need these flags.

2022-03-01 21:57 UTC, nandinivij commented on test_lib/xml_format_checker.py
> +            if contains_XML and contains_log:
![Screen Shot 2022-03-01 at 1 56 21 PM](https://user-images.githubusercontent.com/61885842/156255691-a3e453fe-c85a-44c4-a49c-d1fc134c3dc1.png)
If combination of files we want to add failure case

2022-03-01 23:09 UTC, nandinivij commented on test_lib/xml_format_checker.py
> +            else:
Added check for empty directory.

2022-03-02 13:24 UTC, arys-splunk commented on test_lib/test_cim.py
> +from common_util import *
This import seems to be too wide.

Reference: https://google.github.io/styleguide/pyguide.html#22-imports

2022-03-02 17:59 UTC, nandinivij commented on test_lib/xml_format_checker.py
> +            if contains_XML and contains_log:
Hi, @hsekowski-splunk I am aware of the future scope regarding KO and req test samples, But this PR is to support the .xml or .log files in unit tests. As we already merged the PR to support both in PSA.
**Without this PR** -
Req test - will support .xml or .log
But unit test will throw an error of invalid file format when it finds a .xml file.
https://github.com/splunk/splunk-add-on-for-juniper/runs/5395821561?check_suite_focus=true
<img width="999" alt="Screen Shot 2022-03-02 at 9 46 18 AM" src="https://user-images.githubusercontent.com/61885842/156419022-999e0734-1198-4c89-b277-ab72198f4e5c.png">


**With this PR**
Unit tests will also support both .xml /.log format. 
Added check here -  we restrict the combination of .log and  .xml files in the requirement_test/logs folder. The reasoning behind restricting .log and .xml is when the combination is present it can create confusion if one means different from the other.

This is not a breaking change. I am testing this branch with Juniper addon existing logs. Please find test run here - https://github.com/splunk/splunk-add-on-for-juniper/runs/5396003674?check_suite_focus=true

Hope this explains this PR. Let me know if we need to hop on a quick chat

2022-03-14 17:19 UTC, hsekowski-splunk approved these changes

2022-03-14 17:19 UTC, merged